### ISSUE TITLE
PreCat1GroupOfPreXMod: xmod breaks xmodalg?

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/xmod#106]
XModAlg loading now crashes with an error:
```
===========================================
%%% Loading xmodalg 1.17
#I  polymake command not found. Please set POLYMAKE_COMMAND by hand
#I  method installed for DirectProductOp matches more than one declaration
#I  method installed for SmallGeneratingSet matches more than one declaration
#I  HAP warning: Set POLYMAKE_PATH manually if needed. 
#I  HAP warning: Set ASY_PATH manually if needed.
Error, Variable: 'PreCat1GroupOfPreXMod' must have a value
===========================================

```
- are there any changes in the recent release of XMod causing this?

**Comment by cdwensley** [comment]
That's quite possible - I'll look into it.
Must remember to test XModAlg whenever XMod changes!

**Comment by alex-konovalov** [comment]
@cdwensley please do, as it breaks regression tests for GAP release candidates at the moment.

**Comment by cdwensley** [comment]
XModAlg tests work for me with both 4r11 and gapdev:
```Loading XModAlg 1.18 (07/08/2020) for GAP 4.9 
Methods for crossed modules of commutative algebras and cat1-algebras
by Zekeriya Arvasi (zarvasi@ogu.edu.tr) and Alper Odabas (aodabas@ogu.edu.tr).
-----------------------------------------------------------------------------
true
gap> Read("tst/testall.g");
Architecture: x86_64-apple-darwin17.7.0-default64-kv8

testing: /Applications/gap/my-dev/pkg/xmodalg/tst/cat1.tst
    1379 ms (631 ms GC) and 72.8MB allocated for cat1.tst
testing: /Applications/gap/my-dev/pkg/xmodalg/tst/convert.tst
     571 ms (441 ms GC) and 14.6MB allocated for convert.tst
testing: /Applications/gap/my-dev/pkg/xmodalg/tst/xmod.tst
    1460 ms (374 ms GC) and 84.7MB allocated for xmod.tst
-----------------------------------
total      3410 ms (1446 ms GC) and 172MB allocated
              0 failures in 3 files

#I  No errors detected while testing'''

The error report above says version 1.17 is being loaded - why should that be?

**Comment by cdwensley** [comment]
@alex-konovalov first line missing from the log above:
```Loading XModAlg 1.18 (07/08/2020) for GAP 4.9 '''

**Comment by cdwensley** [comment]
Still missing - obviously I do not understand the " 3` and 3' " syntax.  Try again: 
```
Loading XModAlg 1.18 (07/08/2020) for GAP 4.9 
'''

**Comment by alex-konovalov** [comment]
@cdwensley the syntax is three backticks before and three after. I've fixed this for you above.

You're using XModAlg 1.18, but for me it does not exist - https://gap-packages.github.io/xmodalg/ serves 1.17. Perhaps @aodabas needs to publish a new release?

**Comment by alex-konovalov** [comment]
@cdwensley @aodabas indeed, I see https://github.com/gap-packages/xmodalg/commit/1e47463ebd13532d6cb36e61e601004f0b07dfda so a release should be made.

**Comment by cdwensley** [comment]
@alex-konovalov @aodabas   Apologies - I did not realise that 1.18 had not been released.  (We tend to use 1.17dev until ready for release.)  I will sort that out tomorrow (assuming that Alper is happy for me to do so!).  And then another release of XMod.

**Comment by cdwensley** [comment]
After numerous attempts at making a release I realise I do not have the authority to do so, so leave it to @aodabas.

**Comment by alex-konovalov** [comment]
@cdwensley but I can see that you have write access to xmodalg - or was that just given today after this?

**Comment by cdwensley** [comment]
@alex-konovalov  Yes, I believe that I have had write access for some time - but is that the same as being able to make a release?  My many attempts have failed, but that might be because of general confusion.  Now that @aodabas has merged PR#42 I will have another go, and report back here.

**Comment by cdwensley** [comment]
If @alex-konovalov can make a release, that would be a great help.  
This is what happens for me:
```
ChristoleysiMac:xmodalg christopherwensley$ ../ReleaseTools/release --token ...omitted...
Extracting information from PackageInfo.g...
Package XModAlg 1.18
Building GAP package documentation (using makedoc.g)
Using archive basename XModAlg-1.18
Using GitHub repository gap-packages/xmodalg
Using GitHub username gap-packages
Using branch master
Using git tag v1.18 (derived from ArchiveURL in in PackageInfo.g)

Exporting repository content for tag 'v1.18'
Removing unnecessary files
Building GAP package documentation for archives (using makedoc.g)

Validating PackageInfo.g...

Creating XModAlg-1.18.tar.gz ...
Pushing your branch to GitHub
Counting objects: 23, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (23/23), done.
Writing objects: 100% (23/23), 2.67 KiB | 1.33 MiB/s, done.
Total 23 (delta 15), reused 0 (delta 0)
remote: Resolving deltas: 100% (15/15), completed with 3 local objects.
To https://github.com/gap-packages/xmodalg
   b278230..59127ca  master -> master
Pushing your tag to GitHub
To https://github.com/gap-packages/xmodalg
 ! [rejected]        v1.18 -> v1.18 (already exists)
error: failed to push some refs to 'https://gap-packages:9c1d8ceffd6684f8fbbbd1483a1cfd60220cd308@github.com/gap-packages/xmodalg'
hint: Updates were rejected because the tag already exists in the remote.
'''

**Comment by cdwensley** [comment]
Could this be part of the problem? 
With XMod, Kan, etc. I just have remotes master = gap-packages/xmod and gh-pages. 
But with XModAlg I have master = cdwensley/xmodalg and upstream = gap-packages/xmodalg plus gh-pages.  
So maybe the release script is trying to send stuff to the wrong place?

**Comment by alex-konovalov** [comment]
It says `hint: Updates were rejected because the tag already exists in the remote.` - indeed, there is already v1.18 there. https://github.com/gap-system/ReleaseTools documentation explains `--force` version which can be used to in such cases.

**Comment by cdwensley** [comment]
Thanks:  --force does indeed work.  But the push sends the output to cdwensley, not gap-packages!  Investigating ... 
```
ChristoleysiMac:xmodalg christopherwensley$ cd gh-pages
ChristoleysiMac:gh-pages christopherwensley$ git push
Counting objects: 9, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 722 bytes | 722.00 KiB/s, done.
Total 9 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
To https://github.com/cdwensley/xmodalg
   6498f07..0006b49  gh-pages -> gh-pages

**Comment by cdwensley** [comment]
It appears that the following has worked: 
```
> git push -f upstream 
'''
@alex-konovalov do you agree?

**Comment by alex-konovalov** [comment]
Fixed in https://github.com/gap-packages/xmodalg/issues/40, thanks!
