### ISSUE TITLE
Properly release 2.89

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/xmod#134]
It seems you tried to release 2.89 a few days ago, but something went wrong. E.g. the `gh-pages` branch now lists 2.88dev (but the actual website does not, so it might not even be valid).

Since this release probably also was affected by the same problem as the groupoids release, perhaps best to just redo it?

**Comment by cdwensley** [comment]
Yes, I’m trying hard.  But I have finally realised that part of the double groupoids code should be in Groupoids, and the rest in XMod. 
Expect to release a new Groupoids today, then maybe XMod tomorrow.

**Comment by cdwensley** [comment]
2.89 now superceded by 2.91.
