### ISSUE TITLE
Don't rely on structure description in tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/xmod#21]
When no packages are loaded, new diffs show up when xmod is tested in stable-4.9 GA{ branch: https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/370853283 e.g.
```
########> Diff in /home/gap/inst/gap-stable-4.9/pkg/XMod-2.66/tst/apps.tst:19
# Input is:
Size( LX );  StructureDescription( LX ); 
# Expected output:
[ 8, 64 ]
[ "C2 x C2 x C2", "((C2 x C2 x C2 x C2) : C2) : C2" ]
# But found:
[ 8, 64 ]
[ "C2 x C2 x C2", "(C4 x C2) : D8" ]
########
```
I'd recommend to make tests more robust by relying on `IdGroup` rather than on `StructureDescription`. This will help in the long run, since `StructureDescription` is not guaranteed to return the same decomposition each time.

**Comment by cdwensley** [comment]
@alex-konovalov : OK - I'm happy to do that, and probably in XModAlg

**Comment by cdwensley** [comment]
There are certainly variations when StructureDescription is applied to various 2-groups, but there should be no problem when the answer is "PSL(3,2)" or "C3 x D34" etc.  XMod version 2.67 released 29/04/18 fixes the current problem.
