### ISSUE TITLE
xmod 2.56 test failure

### ISSUE THREAD

**Issue by jamesjer** [gap-packages/xmod#3]
On an x86_64 Linux machine with gap 4.8.4, hap 1.11, utils 0.40, gpd 1.43, and xmod 2.56, the test suite for xmod shows a failure:
# I  Testing xmod/tst/gpd2obj.tst
###### ##> Diff in xmod/tst/gpd2obj.tst, line 24:
# Input is:

PXO := DiscreteNormalPreXModWithObjects( Ga4, k4 );
# Expected output:

homogeneous, discrete groupoid with:
  group: k4 = <[ (1,2)(3,4), (1,3)(2,4) ]> >
objects: [ -9, -8, -7 ]
# I  now need to be able to test:   ok := IsXMod( PM );

<semigroup>
# But found:

homogeneous, discrete groupoid with:
  group: k4 = <[ (1,2)(3,4), (1,3)(2,4) ]> >
objects: [ -9, -8, -7 ]
^ only implemented for single piece mappings at present
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `*' on 2 arguments
###### 
###### ##> Diff in xmod/tst/gpd2obj.tst, line 30:
# Input is:

Source( PXO ); 
# Expected output:

perm homogeneous, discrete groupoid: < k4, [ -9, -8, -7 ] >
# But found:

Error, Variable: 'PXO' must have a value
###### 
# I  Testing xmod/tst/util.tst
# I  Errors detected while testing package xmod

The error about ^ is triggered inside of gpd, namely in gpdhom.gi, line 562 (GroupoidHomomorphismFromSinglePiece):

```
    if not ( ( rayr[pos1] * rims[i] * rayr[posi]^-1 ) in gpr ) then 
        Error( "ray images not all in relevant homset" ); 
    fi;
```

When this happens, the values are:

pos1 = 1
posi = 1
i = 2
rayr = [ morphism from a homogeneous discrete groupoid:
    [ -9, -8, -7 ] -> [ -9, -8, -7 ]
    object homomorphisms:
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    IdentityMapping( k4 )
     ]
rims = [ morphism from a homogeneous discrete groupoid:
    [ -9, -8, -7 ] -> [ -9, -8, -7 ]
    object homomorphisms:
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    , morphism from a homogeneous discrete groupoid:
    [ -9, -8, -7 ] -> [ -9, -8, -7 ]
    object homomorphisms:
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    , morphism from a homogeneous discrete groupoid:
    [ -9, -8, -7 ] -> [ -9, -8, -7 ]
    object homomorphisms:
    IdentityMapping( k4 )
    IdentityMapping( k4 )
    IdentityMapping( k4 )
     ]

**Comment by cdwensley** [comment]
This error has been in the development version for some time, and I have done some work on it which is not yet finished.  I had not realised that it was now a problem in the released version 4.8.4.  That being the case, I hope to make a new release shortly.
