### ISSUE TITLE
Undeclared dependencies?

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/xmod#7]
Loading xmod with `OnlyNeeded` option results in the following warnings:
```
===========================================
%%% Loading xmod 2.58 , only needed
#I  HAP warning: Set POLYMAKE_PATH manually if needed. 
#I  HAP warning: Set NEATO_PATH manually if needed.
#I  HAP warning: Set DOT_PATH manually if needed.
#I  HAP warning: Set DISPLAY_PATH manually if needed.
#I  HAP warning: Set BROWSER_PATH manually if needed.
Syntax warning: unbound global variable in /data/gap-jenkins/workspace/GAP-min\
or-release-test/GAPCOPTS/32build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovac\
s/gap4r8/pkg/Hap1.11/lib/CohomologyOperations/cohodata.gi line 20
newP:=Objectify(GradedAlgebraPresentationType,newP);
                                             ^
Syntax warning: unbound global variable in /data/gap-jenkins/workspace/GAP-min\
or-release-test/GAPCOPTS/32build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovac\
s/gap4r8/pkg/Hap1.11/lib/CohomologyOperations/cohodata.gi line 30
newP:=Objectify(GradedAlgebraPresentationType,newP);
                                             ^
#I  MakeReadOnlyGlobal: GradedAlgebraPresentationType no value bound
[ "ATf", "Cgs", "Igs", "Map", "Ngs", "Pcp", "Sq" ]
### Loaded xmod 2.58 , only needed
===========================================
```

**Comment by cdwensley** [comment]
I'm guessing that this is a Hap problem?  
The function occurs for _me_ in Hap1.11 only as follows: 
    ChristoleysiMac:Hap1.11 christopherwensley$ cd lib
    ChristoleysiMac:lib christopherwensley$ grep -rn GradedAlgebraPresentationType *
    HapPrime/gradedalgebra.gi:53:GradedAlgebraPresentationType :=
    HapPrime/gradedalgebra.gi:108:      GradedAlgebraPresentationType, 
    hap_afterthought.gd:4:MakeReadOnlyGlobal("GradedAlgebraPresentationType");
as I do not have a file: Hap1.11/lib/CohomologyOperations/cohodata.gi 
The main GAP webpage says of Hap: 
      Current version number 1.11.13   (Released 03/11/2015) 
but the Hap website has: 
      The current version 1.11 was released on 5 December 2016. 
so I will load this and see if it makes any difference.

**Comment by cdwensley** [comment]
Can reproduce this problem after downloading Hap1.11.14, but do not understand what it means. 
Have forwarded the report to Graham Ellis.

**Comment by cdwensley** [comment]
Report from Graham:  
I've fixed the problem. See below.
[The reason for my strange code is that HAP loads certain functions only if the Singular package is available. If it is not available then certain HAP functions are not loaded. But these unloaded function names appear in other files which are loaded.  To allow for this, if Singular is not present then the names of the omitted functions are used to create empty functions.
This is probably not the best way to do things, but it would involve a lot of work to change it now.] 
. . . 
gap> LoadPackage("HAP":OnlyNeeded); 
. . . 
Loading HAP 1.11.14 ...
true
